#!/usr/bin/env bash
#Installs Nginx 

apt-get update -y;
apt-get install -y nginx;
sudo mkdir /etc/nginx/html;
sudo touch /etc/nginx/html/index.html;
echo "Hello World!" >> /etc/nginx/html/index.html;
printf %s "server {
    listen      80 default_server;
    listen      [::]:80 default_server;
    root        /etc/ngnix/html;
    index       index.html;
}
" > /etc/nginx/sites-available/default

sudo service ngnix restart
