#!/usr/bin/env bash
#Installs Nginx 

apt update -y;
apt-install -y nginx;
touch /var/www/html/index.html;
echo "Hello World!" | tee -a /var/www/html/index.html;
printf %s "server {
    listen      80 default_server;
    listen      [::]:80 default_server;
    root        /var/www/html;
    index       index.html
}
" > /etc/nginx/sites-available/default

sudo service ngnix restart
