#!/usr/bin/env bash
#Installs Nginx 

sudo apt update -y;
sudo apt-install -y nginx;
sudo touch /var/www/html/index.html;
echo "Hello World!" | sudo tee -a /var/www/html/index.html;
sudo service nginx restart
