#!/usr/bin/env bash
# Redirects 'redirect_me' to another page

apt-get update -y;
apt-get install -y nginx;
sudo mkdir /etc/nginx/html;
sudo touch /etc/nginx/html/index.html;
echo "Hello World!" >> /etc/nginx/html/index.html;
printf %s "server {
    listen      80 default_server;
    listen      [::]:80 default_server;
    root        /etc/nginx/html;
    index       index.html;

    location    /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
